# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azioncli < Formula
  desc "The developer friendly way to interact with Azion"
  homepage "https://github.com/aziontech/azion-cli"
  version "0.45.0"
  license "MIT"

  depends_on "jq"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aziontech/azion-cli/releases/download/0.45.0/azioncli_0.45.0_Darwin_arm64.tar.gz"
      sha256 "9a5a82990968fc7b74b08df444be28ba97384618453e6525ae0ddf7ae35d79bf"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aziontech/azion-cli/releases/download/0.45.0/azioncli_0.45.0_Darwin_x86_64.tar.gz"
      sha256 "f5638a0620698cc50e2141923cb98e6af46f165525c752addfbd20ce62cda0c9"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aziontech/azion-cli/releases/download/0.45.0/azioncli_0.45.0_Linux_arm64.tar.gz"
      sha256 "fc9bb9bf588b21b8849b249f44c4e4c8f046986ceaedb88a528676cb5f16f1de"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aziontech/azion-cli/releases/download/0.45.0/azioncli_0.45.0_Linux_x86_64.tar.gz"
      sha256 "c1d98ee64dc1c6316e423d28eb9f3a8bfe05871bc89dfd4379ac3dd37e0c57b1"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
  end
end
