# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azion < Formula
  desc "The developer friendly way to interact with Azion"
  homepage "https://github.com/aziontech/azion-cli"
  version "1.2.0"
  license "MIT"

  depends_on "jq"

  on_macos do
    url "https://github.com/aziontech/azion-cli/releases/download/1.2.0/azion_1.2.0_darwin_amd64.tar.gz"
    sha256 "e9d46aa3f57f034dbbe4e9a0233da68e820d339a9b643b5c725dfc04ba40d789"

    def install
      bin.install "azion"
      bash_completion.install "completions/azion.bash" => "azion"
      zsh_completion.install "completions/azion.zsh" => "_azion"
      fish_completion.install "completions/azion.fish"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Azion
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aziontech/azion-cli/releases/download/1.2.0/azion_1.2.0_linux_amd64.tar.gz"
      sha256 "93b139f1cc78a3700827e126b3cc0c8ba0a336ad21bf8bc8de87b28d5d39ecb0"

      def install
        bin.install "azion"
        bash_completion.install "completions/azion.bash" => "azion"
        zsh_completion.install "completions/azion.zsh" => "_azion"
        fish_completion.install "completions/azion.fish"
      end
    end
  end
end
