# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azion < Formula
  desc "The developer friendly way to interact with Azion"
  homepage "https://github.com/aziontech/azion-cli"
  version "1.3.0"
  license "MIT"

  depends_on "jq"

  on_macos do
    url "https://github.com/aziontech/azion-cli/releases/download/1.3.0/azion_1.3.0_darwin_amd64.tar.gz"
    sha256 "492d5aade691fbaa24380bc5db1dbaf2a3d3935cfebc236b568411b62bcf7d56"

    def install
      bin.install "azion"
      bash_completion.install "completions/azion.bash" => "azion"
      zsh_completion.install "completions/azion.zsh" => "_azion"
      fish_completion.install "completions/azion.fish"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Azion
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aziontech/azion-cli/releases/download/1.3.0/azion_1.3.0_linux_amd64.tar.gz"
      sha256 "40ff19dfc7241db4d2c310a3bf4e852e0461ccb888455f9c711b452cc77d7b89"

      def install
        bin.install "azion"
        bash_completion.install "completions/azion.bash" => "azion"
        zsh_completion.install "completions/azion.zsh" => "_azion"
        fish_completion.install "completions/azion.fish"
      end
    end
  end
end
