# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azioncli < Formula
  desc "The developer friendly way to interact with Azion"
  homepage "https://github.com/aziontech/azion-cli"
  version "0.43.0"
  license "MIT"

  depends_on "jq"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aziontech/azion-cli/releases/download/0.43.0/azioncli_0.43.0_Darwin_x86_64.tar.gz"
      sha256 "59a5b854a771d7afd0ead445544577f2723707fb967f7ac963ef777abd4480b3"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aziontech/azion-cli/releases/download/0.43.0/azioncli_0.43.0_Darwin_arm64.tar.gz"
      sha256 "35fc7dc70555e6892e547a17f454bad49a1491d0ee4f977757f241654c21dd6c"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aziontech/azion-cli/releases/download/0.43.0/azioncli_0.43.0_Linux_arm64.tar.gz"
      sha256 "611ae9dcf559e3384e66eda5b95993aad5892b37371d7f8234fb56f6b4beaeed"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aziontech/azion-cli/releases/download/0.43.0/azioncli_0.43.0_Linux_x86_64.tar.gz"
      sha256 "917b4eae2de18182848b4af155e59040da9a3b9fa105725ecaf6270e2b23fa02"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
  end
end
