# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azion < Formula
  desc "Interact in a developer friendly way with Azion"
  homepage "https://github.com/aziontech/azion-cli"
  version "1.5.1"
  license "MIT"

  depends_on "jq"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aziontech/azion-cli/releases/download/1.5.1/azion_1.5.1_darwin_amd64.tar.gz"
      sha256 "efe05f723ad2bbf22d307de3287d81d3f347df4c8ddbad0b0d57793e867f9ba9"

      def install
        bin.install "azion"
        bash_completion.install "completions/azion.bash" => "azion"
        zsh_completion.install "completions/azion.zsh" => "_azion"
        fish_completion.install "completions/azion.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aziontech/azion-cli/releases/download/1.5.1/azion_1.5.1_darwin_arm64.tar.gz"
      sha256 "87bb387808cf1a38f21e84ee7c69970c767c7938770789470e373268f60bbb24"

      def install
        bin.install "azion"
        bash_completion.install "completions/azion.bash" => "azion"
        zsh_completion.install "completions/azion.zsh" => "_azion"
        fish_completion.install "completions/azion.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aziontech/azion-cli/releases/download/1.5.1/azion_1.5.1_linux_arm64.tar.gz"
      sha256 "a18916b1fea8d51b7145236740356fd2695a717b8906ee191be9e87eb94d1ee8"

      def install
        bin.install "azion"
        bash_completion.install "completions/azion.bash" => "azion"
        zsh_completion.install "completions/azion.zsh" => "_azion"
        fish_completion.install "completions/azion.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aziontech/azion-cli/releases/download/1.5.1/azion_1.5.1_linux_amd64.tar.gz"
      sha256 "21c83168d5961f15ac31fb86943c2c549c4b6675cd698f69b963b4f8411ef73b"

      def install
        bin.install "azion"
        bash_completion.install "completions/azion.bash" => "azion"
        zsh_completion.install "completions/azion.zsh" => "_azion"
        fish_completion.install "completions/azion.fish"
      end
    end
  end

  test do
    system "#{bin}/azion", "--version"
  end
end
