# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azioncli < Formula
  desc "The developer friendly way to interact with Azion"
  homepage "https://github.com/aziontech/azion-cli"
  version "0.53.0"
  license "MIT"

  depends_on "jq"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aziontech/azion-cli/releases/download/0.53.0/azioncli_0.53.0_Darwin_x86_64.tar.gz"
      sha256 "bcc69fb79112925547b64d6d6af3344287e1ece494927435d69946543496bf03"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aziontech/azion-cli/releases/download/0.53.0/azioncli_0.53.0_Darwin_arm64.tar.gz"
      sha256 "17a46e1ee747f2bdbcba3301cea37d7a175320933a300d39d3e5431236ac3988"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aziontech/azion-cli/releases/download/0.53.0/azioncli_0.53.0_Linux_arm64.tar.gz"
      sha256 "bd23424b899f7e459badd2f019e9ed024dc9e7b95e317093c3c129992cf1b3a7"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aziontech/azion-cli/releases/download/0.53.0/azioncli_0.53.0_Linux_x86_64.tar.gz"
      sha256 "25fe58d256da49e9aac5661ebd4b124d0e129d9683459154a4ee8288570d1236"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
  end
end
